### PR TITLE
Support Debian and initial user creation

### PR DESCRIPTION
**Pull request by marcusianlevine**
Great little role @bingoarun 

I'm building Debian containers so I generalized this role to support both major OS families.

I also added an init.sh script template which can be used to implement initial user and vhost creation.

### CODE REVIEW

**Comment by bingoarun** [comment]
@marcusianlevine : Thank you for your contribution. I will look into your PR today and merge it. Did you also had a chance to look at the failing Travis checks for this PR ?

**Comment by marcusianlevine** [comment]
yeah i've been working on the failing travis build

i tried running the build against my fork and got past the issue these PR commits are having (Travis fails to clone my merge commit on your repo)

on my fork I'm having trouble with the `meta/container.yml` behavior: since we are just using `ansible-container install` to populate the empty `container.yml` file, there is no `from` clause in the service definition. [According to the docs](https://docs.ansible.com/ansible-container/roles/access.html#installing-roles) it's supposed to aggregate the `meta` definition but I get the following error: 
```
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 698, in conductorcmd_build
    "service: {}.".format(service_name)
container.exceptions.AnsibleContainerConfigException: Expecting service to have 'from' attribute. None found when evaluating service: rabbitmq-container.
```

**Comment by marcusianlevine** [comment]
@bingoarun finally got around to working out why this wouldn't build

Turns out some changes upstream to AC led to the test workflow breaking. I ended up fixing that and added tests for the new Debian support as well

**Comment by bingoarun** [comment]
@marcusianlevine : Thank you for all your help on this !!

**Pull request merged**
